"""add RosterDemand junction, remove roster_id from demand

Revision ID: 01481815c843
Revises: 1340995383f5
Create Date: 2026-04-30 08:27:06.369551
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '01481815c843'
down_revision: Union[str, None] = '1340995383f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roster_demand',
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('demand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['demand_id'], ['demand.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['roster_id'], ['roster.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('roster_id', 'demand_id'),
    sa.UniqueConstraint('roster_id', 'demand_id', name='uq_roster_demand')
    )
    op.drop_constraint('demand_roster_id_fkey', 'demand', type_='foreignkey')
    op.drop_column('demand', 'roster_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('demand', sa.Column('roster_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('demand_roster_id_fkey', 'demand', 'roster', ['roster_id'], ['id'], ondelete='CASCADE')
    op.drop_table('roster_demand')
    # ### end Alembic commands ###
